name: open-in-editor
version: 0.1.0.0
synopsis: Open editor based on user preferences
description: |
  Open editor based on user preferences
category: Command Line, Editor, Text

license: BSD3
license-file: LICENSE
author: Peter Trško
maintainer: peter.trsko@gmail.com
copyright: (c) 2019 Peter Trško

extra-source-files:
  - README.md
  - dhall/Editor/*

default-extensions:
  - BlockArguments
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TupleSections
  - TypeApplications

dependencies:
  - base

  - dhall >= 1.23 # Dhall language standard 7.0.0
  - directory
  - process
  - text
  - transformers
  - unix

ghc-options:
  - -Wall

library:
  source-dirs: src
