# For advanced use and comprehensive documentation of the format, please see:
# https://docs.haskellstack.org/en/stable/yaml_configuration/

resolver: lts-15.16

packages:
  - '.'

extra-deps:
  - dhall-1.33.1
  - repline-0.4.0.0
  - haskeline-0.8.0.0
